### ISSUE TITLE
localhost being ignored

### ISSUE THREAD

**Issue by markpanado** [skandasoft/open-in-browsers#36]
It doesn't follow  the set localhost. It still open the php files in files:/// protocol.

![image](https://cloud.githubusercontent.com/assets/3646720/24234654/7c05bd4e-0fd4-11e7-94ed-22256189be0e.png)

![image](https://cloud.githubusercontent.com/assets/3646720/24234676/91041a06-0fd4-11e7-88f6-8bd9f805f872.png)

How I can set this properly?

**Comment by EdwinHuijsing** [comment]
@markpanado did you use `Open in Browser` or `Open in Browsers > Open inFirefox`?

For me the first option gives the same problem as you have.
But opening it with `Open in Browsers > Open inFirefox` works.

Note: you config for `localhost` MUST be correct, for me `http://localhost:3000` is not working. I just use `http://localhost` and it works

HTH

@skandasoft  is there a reason for the different behavior?

**Comment by EdwinHuijsing** [comment]
Due to some cache i had the menu item `Open in Browser`, after restart has been removed an i only had the option `Open in Browsers > ...`.

This time i also tried Chrome and brower-plus.
* Chrome: No response at all. If closed it will not be opened, if open the current tab is not updated and there is no new tab. 
* Browser-plus: opens but it shows the `browser-plus://blank` page.

I only have Chrome and Firefox installed on my Linux machine
Tested the localhost url in the browser before using it.
Installed `Open in Browsers` today.

Update:
Browser-plus opens the file depending on its settings, if `Show Current File` is ticked then `Open in Browsers` will also only show the file if the file is open. For me this is not expected behavior.

**Comment by markpanado** [comment]
@EdwinHuijsing Yes, my localhost url is correct. I don't use the url `http://localhost` I set it up as `http://centos.local` since I'm using a local virtual machine for the web server. The url should not be the problem. The plugin should open a file to the set localhost, but mine still points to the `file:///` protocol.

**Comment by EdwinHuijsing** [comment]
@markpanado Have you test with one browser or more?
I understand that you have an other url for you localhost. While reading more issues i found that in some environments the port is required, for me the 8000, 3000, 8080 are not working.  That's why i asked if the url is correct.

This is how i open the file, for me only Firefox (on Linux) works.
![openinbrowsers](https://cloud.githubusercontent.com/assets/19737514/24590431/f959d030-17ec-11e7-8b1f-9c3aa6ea6ed5.png)

What Browsers have you try?
On What OS(distro) are you on?

Note: In my first replay i had the same problem because i used `Open in Browser` not `Open in Browsers` (the only difference is the s on the end off the name). Open in Browser gives a extra menu option without submenu items. Please check that this is not the one you use, Open in Browser will not use localhost.
Open in Brower**s** should (for me only in Firefox)

**Comment by markpanado** [comment]
@EdwinHuijsing Yes, I tried to pick Toggle, Chrome, and Firefox both via Command Palette and right clicking it with no success.

I'm using macOS. 

This is what is showing to me:

![image](https://cloud.githubusercontent.com/assets/3646720/24595168/963e80fc-1866-11e7-98c8-840640b0e514.png)

![image](https://cloud.githubusercontent.com/assets/3646720/24595177/b1d6fcc2-1866-11e7-9072-0d34e9afca59.png)

![image](https://cloud.githubusercontent.com/assets/3646720/24595192/cfb62bd2-1866-11e7-871e-9508a9ba01fe.png)

![image](https://cloud.githubusercontent.com/assets/3646720/24595199/ede0eea8-1866-11e7-9dac-1b6699bc2163.png)

**Comment by EdwinHuijsing** [comment]
@markpanado Sorry but I can't reproduce it.

There is only one problem that happened to me with setting in Atom Plugins, the first time changing them they did NOT get saved (or not all got saved). I had to update the settings a second time before the setting got saved.
Please check if the `LocalHost URL`  is still ticked, for now that's the only thing i can think of.

**Comment by danchamorro** [comment]
When choosing to open in chrome it opens up Parallels on my Mac. Even though Parallels is not open it will open it and bring me to the login page of the Windows desktop in parallels. The other browsers work fine, Safari and Firefox. 

UPDATE: This was a setting in Parallels which cause this to happen. Works perfectly now.

**Comment by skandasoft** [comment]
same as #17 . follow that lssue
